- name: build and run container
  hosts: docker
  become: yes
  become_user: dockerhost

  tasks:
  - name: stop running container
    command: docker stop react-app
    ignore_errors: yes

  - name: delete the container
    command: docker rm react-app
    ignore_errors: yes

  - name: delete the image
    command: docker rmi gauravpadwal/react-jenkins-ansible:latest
    ignore_errors: yes

  - name: pull the image
    command: docker pull gauravpadwal/react-jenkins-ansible:latest

  - name: run the container
    command: docker run --name react-app -d -p 80:80 gauravpadwal/react-jenkins-ansible:latest